### ISSUE TITLE
E2E-Tests are failing CI

### ISSUE THREAD

**Issue by tzaffi** [algorand/indexer#1521]
## Make the tests 🟢 

Tests that regularly fail suffer from the "boy who cried wolf" syndrome: you can get so complacent about the tests failing and assume that the failure was a false alarm so as to miss a real and relevant failure that has cropped up.

### Tasks

- [x] Alerts are sent only to `#lamprey-builds` channel
- [x] This should be managed by
  - [x] new `lamprey-secrets` Circle context
  - [x] new `lamprey-notify` Slack app
- [x] Update E2E tests to latest network available on AWS
- [x] All tests pass
- [x] Turn the tests back on for the **On-Commit** workflow

### Related
* #1524
* go-algorand-sdk PR: https://github.com/algorand/go-algorand-sdk/pull/531
* #1523 
* conduit PR: https://github.com/algorand/conduit/pull/73
* go-algorand PR: https://github.com/algorand/go-algorand/pull/5381 for cross-repo type checking

**Comment by tzaffi** [comment]
Latest nightly job has passed.
